# Generated by Django 4.0.1 on 2022-05-10 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main1', '0005_alter_myuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='img',
            field=models.ImageField(default=1, upload_to='Blog/'),
            preserve_default=False,
        ),
    ]
